# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NameServer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10NameServer.proto\x12\x12NameServer_service\"\t\n\x07nothing\" \n\x0ctestResponse\x12\x10\n\x08mesnsaje\x18\x01 \x01(\t\"+\n\x18GetChatParametersRequest\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t\":\n\x19GetChatParametersResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"K\n\x15RegisterClientRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\nip_address\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\")\n\x16RegisterClientResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb5\x02\n\x11NameServerService\x12p\n\x11GetChatParameters\x12,.NameServer_service.GetChatParametersRequest\x1a-.NameServer_service.GetChatParametersResponse\x12g\n\x0eRegisterClient\x12).NameServer_service.RegisterClientRequest\x1a*.NameServer_service.RegisterClientResponse\x12\x45\n\x04test\x12\x1b.NameServer_service.nothing\x1a .NameServer_service.testResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NameServer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTHING']._serialized_start=40
  _globals['_NOTHING']._serialized_end=49
  _globals['_TESTRESPONSE']._serialized_start=51
  _globals['_TESTRESPONSE']._serialized_end=83
  _globals['_GETCHATPARAMETERSREQUEST']._serialized_start=85
  _globals['_GETCHATPARAMETERSREQUEST']._serialized_end=128
  _globals['_GETCHATPARAMETERSRESPONSE']._serialized_start=130
  _globals['_GETCHATPARAMETERSRESPONSE']._serialized_end=188
  _globals['_REGISTERCLIENTREQUEST']._serialized_start=190
  _globals['_REGISTERCLIENTREQUEST']._serialized_end=265
  _globals['_REGISTERCLIENTRESPONSE']._serialized_start=267
  _globals['_REGISTERCLIENTRESPONSE']._serialized_end=308
  _globals['_NAMESERVERSERVICE']._serialized_start=311
  _globals['_NAMESERVERSERVICE']._serialized_end=620
# @@protoc_insertion_point(module_scope)
